### ISSUE TITLE
Sequential validation after onBlur on required fields

### ISSUE THREAD

**Issue by 3runoDesign** [bmvantunes/youtube-2020-june-multi-step-form-formik#7]
After the 'OnBlur' event in any mandatory field ... all other fields with any validation are triggered as invalid.

One of my approaches was to customize my fields for these types of forms...
```js
...
onBlur={() => helpers.setTouched(true)}
...
```
`But I really don't know what the best approach would be!.`

https://codesandbox.io/s/polished-dew-8ns0u?file=/src/pages/index.tsx
Such an exception occurs only in subsequent steps.

Thanks!!

**Comment by bmvantunes** [comment]
Any news regarding this one? :)

**Comment by 3runoDesign** [comment]
@bmvantunes i got a solution by resetting the "touched" to go to the next step...

https://codesandbox.io/s/polished-dew-8ns0u?file=/src/pages/index.tsx:4143-4176
